# manifest for clusterip
apiVersion: v1
kind: Service
metadata: 
   name: my-service
spec: 
   selector:
      app: my-app
   type: ClusterIP
   ports: 
     - port: 8080
       targetPort: 80
       protocol: TCP            
