apiVersion: v1
kind: Pod
metadata: 
  name: my-pod-3
  namespace: my-new-ns   
  labels: 
      app: my-app
spec: 
  containers:
    - name: my-cont1
      image: nginx
      ports:
        - containerPort: 80   
